name: Publish to Test PyPI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (optional, will use pyproject.toml version if not specified)'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine build

    - name: Build package
      run: python -m build

    - name: Publish package to Test PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
      run: twine upload --repository-url https://test.pypi.org/legacy/ dist/*